### ISSUE TITLE
Galaxy-MSM8916 discussion

### ISSUE THREAD

**Issue by zqm64** [zqm64/discussion#1]
@SebaUbuntu Do you see my message on https://github.com/samsung-msm8916-dev/android_device_samsung_j5x3gxx/issues ?
Because I can't use gmail these days.

**Comment by SebaUbuntu** [comment]
I see no issues (messages) here

**Comment by zqm64** [comment]
Ok Then Let me send it here. It's very IMPORTANT.

**Comment by zqm64** [comment]
Execute this to show my message:

> echo '0l2dgcmbptGbhRHIy9mZgcmbpNXdgMXY3BSSgg2Yph2dgwWah1WZgUGa0BiL0YTbxpHItdSSgkGS
NByUJhEVgUURTBSVPlFISVEVGFkCu0VbvNmLslWYtdGQ0YzZulWbpF3ZuVGa6tFIzlGIsU3b5BCa
tBycphGVKESIZx0SDlUVRBSRVN1UJBiQVhEVJdEIFhEVgoiKFRUSIpiKgU0UBVETQBCLFdUQTNVR
gUESUBSWCBCRFt0QPxkQgckTJRFVFdEITlEISVkVSV0UgkFWPJFUgUEVBZVSSBFIZ1EIn5WauJ3b
hVWbgQXYoRlCuQXZuJXZ05WagwWYi9GbnBSZoRHIn5WazNXZjNWYgI3bmBycpBCajlGa3BCLXZ0R
t92Qg4SMKozchBCajV3cgwycn5WaoRHI55WYtBybkByb0BSZsJWYgUmYgQ3buBCbsl2dgkEIsMnb
gkHdpxWY1FXLodWaoBCdldEIuIjCuUmcvZWZiBychBSZrlGbgMXYgU3b5BCa0l2dgUGdhNWauVXb
shGdv9WbzBCdpJncldGIy9GIiVHa0l2ZgUGa0BSZzd3byJEIuMjCuUGbn92bnBibvBycyV2dz5WY
5JGIkV2aj9GbiBicvBib39GZgQWZ39GbzBycpBCdhhGdgMXZslmZgcWaiBCZh9Gbud3bEBiL0oQe
sxWZ0BSZzFWZsBlCyVGa0JXdmBSbhJ3ZlxWZUBSZzVHIvRHIrNWYiBCdldEIuUjCuclRHBSZoRHI
gU3b5BCZsV3bDBCZuFkCztmbhhGVgEybvRHIxonbp1GQgQmbhBCO3YjMlNmbpZHQg8GdgMXaoRHI
gwSZyF2d0Z2bzByay92d0VmbgkHdp1Weu9mbhBSYoAiIQJTSiASYgUWbgQXZnByb0BSZtBCcsVGa
kl2clJkChECdvxGIhBycr5WYoRFI/MXZslmZgoiKkVWZzVmcqoCIzRXaggGdpdHIpI3bUBSZrlGb
uV2YlJHI05WZtB3bsVmdlRGI2ETO400UN1Se4FGbhdEIvRHIkVmblBHchhGI0FGaXBCLzlGa0BSZ
lhGdgQmbhBCL5xGduV2YlJHI0VWa1FHI5JXZ2BSZydSelhGVgQXYoRHIltWasByctVWZTByP5xGd
scmbptGbhRHIyVGa0JXdmBicvZkCK4ib39GZgkHb05WZyJXdjBycpBiclZnclNHI0lmcyV2ZgIXa
u9WazNXdjNXak9CN20Wc69SbvNmLiVHa0l2Zv8iOzBHd0hGI6UmclhGIvRHIlZ3btBSZzFWZsBHI
lhGVgwCduVWbw9GblZXZkBSZoRHI0V3biFGIn5WarxWY0BCdzVnagUmcnU3b5BiZJpwclV3czl2L
n5WarxWY0BSZydSdvlHImlEI0VnQK4SZyVGag42bgQ3cvBHI5xGctl2cgQ3c1pGIuF2YgU3b5Bib
lJGItVGa0BCdwlncj5WZg8GdgIXZkl2cu92YgU2chVGbQBCLlNHblByZulGa0VWbvNHI0V3biFGI
tBibvlGdwlncj5WZgMXaoRHIlNXdgwGbpdHIJBSZyVHd1ZGIlhGdg4WSKoQIn5Wa0N3bwBSZy9mZ
gQjNlNXYi1CIZV0SgsWLgMmYj1iN1ITLzVWYgw2cz5WZw9GI8ByJUhVRUdCIvh2YltlC6Q2boRXZ
vh2YltlC6Qmbh1WbvNGIzlGa0ByZul2c1BSblhGdgQHc5J3YlRGIuF2YgU3b5BCZuFkCdZXZyBCf
tACN2U2chJWLgkVRLByatAyYiNWL2UjMtMXZhBCbzNnblB3bgwHI2VmcgwHInQURUBVWSNkTFdCI
2MmZ0MWLxADOh1iYxgDNtITYxATL4Q2NihjN3AzWKozcpBSeltEIu9Wa0BXeyNmbFBSZoRlCK0FZ
K0VYlBzN5kDN' | rev | base64 -d

**Comment by zqm64** [comment]
@SebaUbuntu Tell me after reading this message! I have to delete it.

**Comment by SebaUbuntu** [comment]
Received
